import { LocalDict } from "../../lang";

export const nomenclatureDict: Record<"en" | "ru", LocalDict> = {
  en: {
    mono_num: "mono",
    un_num: "un",
    he_num: "he",
    hen_num: "hen",
    ki_num: "ki",
    di_num: "di",
    do_num: "do",
    tri_num: "tri",
    tria_num: "tria",
    tetra_num: "tetra",
    penta_num: "penta",
    hexa_num: "hexa",
    hepta_num: "hepta",
    octa_num: "octa",
    nona_num: "nona",
    deca_num: "deca",
    icosa_num: "icosa",
    cosa_num: "cosa",
    conta_num: "conta",
    conti_num: "conti",
    cta_num: "cta",
    lia_num: "lia",

    bis_num: "bis",
    tris_num: "tris",
    ter_num: "ter",
    quater_num: "quater",
    quinque_num: "quinque",
    sexi_num: "sexi",
    septi_num: "septi",
    octi_num: "octi",
    novi_num: "novi",
    deci_num: "deci",
    kis_num: "kis",

    "Cant build PIN": "Failed to construct preferred IUPAC name from formula",
  },
  ru: {
    mono_num: "моно",
    un_num: "ун",
    he_num: "ге",
    hen_num: "ген",
    ki_num: "ки",
    di_num: "ди",
    do_num: "до",
    tri_num: "три",
    tria_num: "триа",
    tetra_num: "тетра",
    penta_num: "пента",
    hexa_num: "гекса",
    hepta_num: "гепта",
    octa_num: "окта",
    nona_num: "нона",
    deca_num: "дека",
    icosa_num: "эйкоза",
    cosa_num: "коза",
    conta_num: "конта",
    conti_num: "конти",
    cta_num: "кта",
    lia_num: "лия",

    bis_num: "бис",
    tris_num: "трис",
    ter_num: "тер",
    quater_num: "кватер",
    quinque_num: "кинке",
    sexi_num: "секси",
    septi_num: "септи",
    octi_num: "окти",
    novi_num: "нови",
    deci_num: "деци",

    kis_num: "кис",

    "Cant build PIN": "Не удалось построить название из формулы",
  },
};
